PLOS/wombat

src/main/java/org/ambraproject/wombat/config/RuntimeConfiguration.java, src/main/java/org/ambraproject/wombat/config/SpringConfiguration.java, src/main/java/org/ambraproject/wombat/config/YamlConfiguration.java, src/main/java/org/ambraproject/wombat/config/site/SiteSet.java, src/main/java/org/ambraproject/wombat/config/site/SiteTemplateLoader.java, src/main/java/org/ambraproject/wombat/config/theme/FileTheme.java, src/main/java/org/ambraproject/wombat/config/theme/FilesystemThemeSource.java, src/main/java/org/ambraproject/wombat/config/theme/InternalTheme.java, src/main/java/org/ambraproject/wombat/config/theme/Theme.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeBuilder.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeDebugInfo.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeSource.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeTree.java, src/main/java/org/ambraproject/wombat/controller/AppRootPage.java, src/main/java/org/ambraproject/wombat/controller/FigurePageController.java, src/main/java/org/ambraproject/wombat/controller/PowerPointController.java, src/main/java/org/ambraproject/wombat/service/ArticleServiceImpl.java, src/main/java/org/ambraproject/wombat/service/CommentServiceImpl.java, src/main/java/org/ambraproject/wombat/service/remote/UserApiImpl.java, src/main/webapp/WEB-INF/themes/root/app/approot.ftl, src/test/java/org/ambraproject/wombat/config/TestRuntimeConfiguration.java, src/test/java/org/ambraproject/wombat/config/TestSpringConfiguration.java, src/test/java/org/ambraproject/wombat/config/theme/StubTheme.java, src/test/java/org/ambraproject/wombat/config/theme/TestClasspathTheme.java, src/test/java/org/ambraproject/wombat/config/theme/ThemeTreeTest.java, src/test/java/org/ambraproject/wombat/controller/ArticleControllerTest.java, src/test/java/org/ambraproject/wombat/controller/StaticResourceControllerTest.java
Note: will require a wombat.yaml update after merging.
=> DPRO-3346: Move theme tree structure from wombat.yaml

src/main/java/org/ambraproject/wombat/config/SpringConfiguration.java, src/main/java/org/ambraproject/wombat/config/site/SiteSet.java, src/main/java/org/ambraproject/wombat/config/theme/Theme.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeBuilder.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeDebugInfo.java, src/main/java/org/ambraproject/wombat/config/theme/ThemeGraph.java, src/main/java/org/ambraproject/wombat/controller/AppRootPage.java, src/test/java/org/ambraproject/wombat/config/TestSpringConfiguration.java, src/test/java/org/ambraproject/wombat/config/theme/ThemeGraphTest.java
=> DPRO-3346: Rename ThemeTree to ThemeGraph

pom.xml, src/deb/README.md, src/deb/control/control, src/deb/control/postinst, src/deb/control/preinst
Swarmed with @anilop , @rskonnord-plos
=> Dev dpro 3287

src/deb/control/control
=> DPRO-3287: add plos-themes as deb dependency

pom.xml, src/main/java/org/ambraproject/wombat/service/remote/ArticleSearchQuery.java
=> DPRO-3354: lucene-escape special characters sent to solr

src/main/java/org/ambraproject/wombat/service/DoiToJournalResolutionService.java, src/main/java/org/ambraproject/wombat/service/remote/ArticleSearchQuery.java, src/main/java/org/ambraproject/wombat/service/remote/SolrSearchApiImpl.java, src/main/webapp/WEB-INF/themes/desktop/resource/js/pages/advanced_search.js
=> Dev dpro 3379

src/main/webapp/WEB-INF/themes/desktop/resource/js/pages/advanced_search.js
Reverting to previous state - merging.
=> DPRO-3379: remove escaping from search

src/main/webapp/WEB-INF/themes/desktop/sass/sections/_header.scss
Assign to the css class plosntd the same properties as the plosone css class.
This change goes together with same branch name in plos-theme (with the images).
=> DPRO-3426 Apply the same style of the PlosOne journal to the NTD to show the anniversary logo

src/deb/tomcat7/conf/logging.properties
=> DPRO-3421: increase embedded Tomcat log level to WARNING

src/main/java/org/ambraproject/wombat/controller/ArticleAssetController.java
=> RARO-125: tie pdf and xml downloads to bucket name

src/main/java/org/ambraproject/wombat/config/RuntimeConfiguration.java, src/main/java/org/ambraproject/wombat/config/YamlConfiguration.java, src/main/java/org/ambraproject/wombat/freemarker/GlobalConfigDirective.java, src/main/java/org/ambraproject/wombat/service/remote/SolrSearchApiImpl.java, src/test/java/org/ambraproject/wombat/config/TestRuntimeConfiguration.java
=> RARO-88: break out solr configuration

src/main/webapp/WEB-INF/themes/desktop/ftl/common/header/search.ftl, src/main/webapp/WEB-INF/themes/desktop/sass/ApertaRxiv/components/_forms.scss, src/main/webapp/WEB-INF/themes/desktop/sass/ApertaRxiv/components/_headerfooter.scss, src/main/webapp/WEB-INF/themes/desktop/sass/ApertaRxiv/components/_scaffold.scss, src/main/webapp/WEB-INF/themes/desktop/sass/ApertaRxiv/vendor/kube/_variables-arxiv.scss
has matching plod-themes pull request
=> RARO-443 - header

src/main/webapp/WEB-INF/themes/desktop/ftl/article/figure.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/figures.ftl, src/main/webapp/WEB-INF/themes/mobile/ftl/article/figures.ftl, src/main/webapp/WEB-INF/themes/root/ftl/article/backToArticleLink.ftl, src/main/webapp/WEB-INF/themes/root/ftl/article/figureList.ftl
Copy of the mobile figures page with slight modifications to the header/footer for desktop.
=> RARO-391: copy mobile figures page for desktop

src/main/webapp/WEB-INF/themes/desktop/ftl/article/articleJs.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/browse/subjectArea/browseSubjectArea.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/search/searchResults.ftl, src/main/webapp/WEB-INF/themes/mobile/ftl/article/metrics.ftl, src/main/webapp/WEB-INF/themes/root/ftl/common/almQueryJs.ftl, src/main/webapp/WEB-INF/themes/root/resource/js/util/counter_query.js, src/main/webapp/WEB-INF/themes/root/resource/js/util/counter_query_promise.js
merge https://github.com/PLOS/wombat/pull/1310 first
=> Dev raro 409

src/main/webapp/WEB-INF/themes/root/resource/js/components/metrics_cited_section.js
=> RARO-742: Google Scholar search does not include doi resolver host

src/main/webapp/WEB-INF/themes/desktop/ftl/article/signposts.ftl, src/main/webapp/WEB-INF/themes/desktop/resource/js/components/signposts.js, src/main/webapp/WEB-INF/themes/root/ftl/common/counterJs.ftl, src/main/webapp/WEB-INF/themes/root/resource/js/components/metrics_viewed_section.js, src/main/webapp/WEB-INF/themes/root/resource/js/pages/metrics_tab.js
Reference: https://github.com/PLOS/wombat/pull/1345
=> RARO-912: reinstating counter changes

src/main/webapp/WEB-INF/themes/desktop/ftl/article/signposts.ftl, src/main/webapp/WEB-INF/themes/desktop/resource/js/components/signposts.js, src/main/webapp/WEB-INF/themes/root/ftl/common/counterJs.ftl, src/main/webapp/WEB-INF/themes/root/resource/js/components/metrics_viewed_section.js, src/main/webapp/WEB-INF/themes/root/resource/js/pages/metrics_tab.js
=> Revert "RARO-912: reinstating counter changes"

src/main/java/org/ambraproject/wombat/config/RootConfiguration.java, src/main/java/org/ambraproject/wombat/config/RuntimeConfiguration.java, src/main/java/org/ambraproject/wombat/config/YamlConfiguration.java, src/main/java/org/ambraproject/wombat/config/yaml/IgnoreMissingPropertyConstructor.java, src/main/java/org/ambraproject/wombat/service/remote/UserApiImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/test/java/org/ambraproject/wombat/config/TestRuntimeConfiguration.java
This PR removes the security risk with having the NED login credentials available through a Rhino endpoint.
* the NED login credentials will be set in the wombat YAML
* added option to YAML configuration code to ignore missing association between YAML property and a JavaBean
Note, this PR requires the [#55 Salt formula pull request](https://github.com/PLOS-Formulas/wombat-formula/pull/55).
=> PLT-1671 : Removed Wombat dependency on Rhino User API endpoint.

src/main/webapp/WEB-INF/themes/desktop/sass/browse-subject-area.scss
=> AMBR-25: improve striking image sizing on browse

src/main/webapp/WEB-INF/themes/desktop/ftl/home/articleCard.ftl, src/main/webapp/WEB-INF/themes/desktop/sass/browse-subject-area.scss
=> AMBR-25: increase thumbnail image size to medium

src/main/webapp/WEB-INF/themes/desktop/ftl/common/siteMenu/siteMenu.ftl
This PR is to support the removal of the "System Help" link in Publish tab on Bio homepage.
=> AMBR-219 : Added macro to create a call out menu with a single submit button.

src/main/webapp/WEB-INF/themes/desktop/sass/sections/home/_subscription.scss
=> Revert "AMBR-382: Add checkbox for active consent to newsletter sign up on jo…"

src/main/webapp/WEB-INF/themes/desktop/sass/related-content.scss
This PR adds CSS tweaks to the `media-coverage-modal` element in the media curation popup.
=> AMBR-409 : CSS changes to support parent DIV container.

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss
Modified CSS to correct image alignment.
=> AMBR-422 : Centered ORCID image vertically.

TeamCity_deployment_script.bash
Related JIRA ticket: https://jira.plos.org/jira/browse/AMBR-325
Added bash file to keep the code for TeamCity deployment job (build step).
=> AMBR-325 add script for TeamCity deployment job

src/main/webapp/WEB-INF/themes/mobile/ftl/common/bodyJs.ftl
=> Revert "AMBR-473 - get ed board working on mobile"

src/main/java/org/ambraproject/wombat/config/site/RequestMappingContextDictionary.java, src/main/java/org/ambraproject/wombat/controller/ArticleController.java, src/main/java/org/ambraproject/wombat/controller/ArticleMetadata.java, src/main/java/org/ambraproject/wombat/identity/ArticlePointer.java, src/main/java/org/ambraproject/wombat/service/ArticleResolutionService.java, src/test/java/org/ambraproject/wombat/controller/ArticleControllerTest.java, src/test/java/org/ambraproject/wombat/controller/ArticleMetadataTest.java, src/test/java/org/ambraproject/wombat/controller/WombatControllerTestConfig.java, src/test/java/org/ambraproject/wombat/freemarker/HtmlElementTransformationTest.java, src/test/java/org/ambraproject/wombat/model/SearchFilterFactoryTest.java, src/test/java/org/ambraproject/wombat/service/ArticleResolutionServiceTest.java, src/test/java/org/ambraproject/wombat/service/SearchFilterServiceTest.java, src/test/java/org/ambraproject/wombat/service/remote/SolrSearchApiTest.java
Increased test coverage of wombat. Some refactoring of production code, such as increasing the visibility of some private methods and final classes, was needed for unit testing.
The refactoring in the first couple of commits are not required for testing, it was just me learning the code base.
=> AMBR-468 more test covg

src/main/webapp/WEB-INF/themes/desktop/resource/js/components/twitter_module.js
=> AMBR-602 - make sure twitter image url is https

pom.xml
=> Use apt-repo plugin to install dev in /var/tmp/apt

src/main/webapp/WEB-INF/themes/desktop/ftl/search/searchInputBar.ftl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-699
This PR escapes the value parameter for the search input field that can be exploited in an XSS attack. 
=> AMBR-699 Escaping value of search input

src/main/webapp/WEB-INF/themes/mobile/ftl/search/searchResults.ftl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-699
https://github.com/PLOS/wombat/pull/1478
This is a follow up PR for AMBR-699. It was sent back because it did not close the XSS vulnerability for the mobile search. 
This bug is difficult to reproduce based on your environment. iOS and Chrome will actively escape and prevent the attack from the URL. I was able to reproduce the issue using Firefox and the spoofing my UserAgent string using a browser extension.
=> AMBR-699 Closing XSS vulnerability for mobile search

src/main/webapp/WEB-INF/themes/desktop/sass/_utilities.scss, src/main/webapp/WEB-INF/themes/desktop/sass/_variables.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-lightbox.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/_header.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/home/_carousel.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-741
These are fixes for PLOS ONE rebrand changes, post QA feedback.
*Changes*
- Fixed carousel button hover for all other journals
- Fixed PONE download button hover on article page
- Fixed PONE related articles link color
- Fixed PONE _Submit Now_ link hover color in mega menu
- Added PLOS Collections brand color (blue)
=> Ambr 735 pone rebrand fixes

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-218
None.
Upgrade to maven tomcat plugin 7 for local development purposes. This brings us in line with the version of tomcat we use in production.
This will have no effect on QA/testing or production.
=> AMBR-218 Upgrade maven tomcat plugin to 7

src/main/webapp/WEB-INF/themes/desktop/sass/_components.scss, src/main/webapp/WEB-INF/themes/desktop/sass/_typography.scss, src/main/webapp/WEB-INF/themes/desktop/sass/_utilities.scss, src/main/webapp/WEB-INF/themes/desktop/sass/_variables.scss, src/main/webapp/WEB-INF/themes/desktop/sass/browse-issue.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-lightbox.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_home.scss, src/main/webapp/WEB-INF/themes/desktop/sass/related-content.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/ambra/_forms.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/home/_carousel.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/home/_subscription.scss, src/main/webapp/WEB-INF/themes/desktop/sass/site-content.scss, src/main/webapp/WEB-INF/themes/root/ftl/article/relatedContentBody.ftl
*JIRA issues* 
https://jira.plos.org/jira/browse/AMBR-772
https://jira.plos.org/jira/browse/AMBR-776
https://jira.plos.org/jira/browse/AMBR-778
https://jira.plos.org/jira/browse/AMBR-779
This PR addresses a handful of bugs/regressions that were reported after the most recent PLOS ONE rebrand changes were released.
- **IE11**: Subscription Box email input field height & placeholder text 
- **Links**: Underlined links for clarification & changed link colors from grey to journal brand (across article pages and static/documentation pages)
- **Collections** branding--reverted back to blue
- Fixed **author byline** jumping behavior (names moved around _onClick_)
- Changed **subscription success message** background color from solid Aperta green to a transparent PLOS ONE teal, just to tone …
=> Ambr 777 author byline

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_home.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/_footer.scss
*JIRA issue:* 
https://jira.plos.org/jira/browse/AMBR-790
https://jira.plos.org/jira/browse/AMBR-791
Fixes link hover behavior in footer and blog header.
=> Ambr 790 footer links

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_static-publish.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/plos-one/_sticky-footer.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-796
Typography looked squished, and new lime color made link text unreadable, as well as the white text in container at the bottom of the page.
Static page typography and color scheme needed a bath ;-)
=> AMBR-796 General improvements to typography and color scheme

pom.xml, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_home.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_static-publish.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/_footer.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/plos-one/_sticky-footer.scss
We rolled back the release but we still want to merge changes made in the release to develop
=> V3.7.4rc merge to develop

pom.xml
This reverts commit 12a64344cfed595e97259cfeeb5dd09677cc202f.
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-803
We're reverting the tomcat maven plugin upgrade.  Because all of the other changes in the release were style changes, suspicion naturally falls on this commit. We want to do another release with only style changes to confirm our suspicion that they are not the cause.
=> Revert "AMBR-218 Upgrade maven tomcat plugin to 7"

pom.xml
This reverts commit c82bbdebba809a3d26aa44f617e15632385bf5ad.
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-803
Reverts the revert we did in https://github.com/PLOS/wombat/pull/1489
We are no longer planning to push just the style changes.
I proved this works by starting tomcat locally:
`mvn tomcat7:run -Dmaven.tomcat.port=8080 -Dwombat.configDir=/etc/ambra`
=> Revert "AMBR-803 Revert "AMBR-218 Upgrade maven tomcat plugin to 7""

src/main/java/org/ambraproject/wombat/service/AssetServiceImpl.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-810
Fixes synchronization to avoid a global lock in some core code.
Ad-hoc analysis with jvisualvm showed that java was spending a lot of time in the `getCompiledAssetLink` method. I guessed that this is probably because there is a global lock there.
As background, wombat includes (wrongly, in my opinion) a runtime asset compilation method which compiles the assets and then caches them. Because it would be a bad idea to compile the assets in multiple threads at once, there is a lock around the compilation process. Unfortunately, this lock was also around the code that generates a unique hash to look up whether the compilation needs to occur. Also unfortunately, this was a global lock. This means that this code is essentially single …
=> AMBR-810 Fix synchronized statement to avoid a global lock

src/main/webapp/WEB-INF/themes/mobile/resource/css/interface.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/mobile.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-738
https://github.com/PLOS/plos-themes/pull/949
This PR updates the PLOS ONE brand colors and logo for mobile.
=> Ambr 738  rebrand mobile

src/main/webapp/WEB-INF/themes/desktop/ftl/article/peerReview.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/tabs.ftl, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-808
This PR provides the HTML and CSS for the new Peer Review tab on the journal article pages. Some things to note:
- Entire peer review history is displayed in a table, in reverse chronological order
- Includes microdata to describe review content (based on schema.org)
- Each submitted version is displayed as follows:
-- section header with version number
-- decision letter & attachments (if available) 
-- author response (if available)
- This PR also includes a change to the tab order: the Peer Review tab has been moved to the end, which makes for a cleaner interaction, as it won't always be present.
- An author response currently has no microdata associated with it.
- This PR does not include any expand/collapse functionality (which …
=> Ambr 808 tpr prototype

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-801
Upgrades to httpclient 4.3.6
=> AMBR-801 Upgrade httpclient to 4.3.6

src/main/resources/peer-review-transform.xsl, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceTest.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-657
*Related PRs:* AMBR-632
Renders author's response in peer review history (which is displayed in new Peer Review tab).
=> AMBR-657: render author response in peer review history.

src/main/webapp/WEB-INF/themes/mobile/resource/css/interface.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/mobile.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-738
https://github.com/PLOS/plos-themes/pull/951
Addresses some color contrast issues: made form backgrounds grey and active link color on pagination black 
<hr />
I chose not do the following:
=> AMBR-738 Some color tweaks to form backgrounds and links

src/main/webapp/WEB-INF/themes/mobile/resource/css/base.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-839
https://github.com/PLOS/plos-themes/pull/952
Adjusts color scheme for static page, post-rebrand on mobile, to optimize for readability and color contrast.
<hr/>
I did not do these:
=> AMBR-839 Address display of static page on mobile for PONE

src/main/java/org/ambraproject/wombat/service/PeerReviewServiceImpl.java, src/main/resources/peer-review-transform.xsl, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss, src/main/webapp/WEB-INF/themes/mobile/resource/css/peer-review.css, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceTest.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-833
Presents the Acceptance Letter at the end of the Peer Review table. under the "Formally Accepted" header.
=> Ambr 833 accept letter

src/main/webapp/WEB-INF/themes/mobile/ftl/article/metrics.ftl, src/main/webapp/WEB-INF/themes/mobile/resource/css/content.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/interface.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/metrics.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-837
Fixes this lovely side-effect:
=> Ambr 837 mobile readability optimizations

src/main/java/org/ambraproject/wombat/controller/ArticleController.java, src/main/java/org/ambraproject/wombat/controller/GeneralDoiController.java, src/main/java/org/ambraproject/wombat/controller/PeerReviewController.java, src/main/resources/peer-review-transform.xsl, src/main/webapp/WEB-INF/themes/root/resource/js/pages/peer-review.js, src/test/java/org/ambraproject/wombat/controller/ArticleControllerTest.java, src/test/java/org/ambraproject/wombat/controller/PeerReviewControllerTest.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-860
Resolves a review DOI to the article's peer review page with the chosen review expanded.
=> Ambr 860 resolve review doi

pom.xml, src/main/java/org/ambraproject/wombat/service/PeerReviewServiceImpl.java, src/main/java/org/ambraproject/wombat/service/XmlUtil.java, src/main/java/org/ambraproject/wombat/service/remote/ContentKey.java, src/main/resources/peer-review-transform.xsl, src/test/java/org/ambraproject/wombat/freemarker/HtmlElementTransformationTest.java, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceTest.java, src/test/resources/peer-review/article-received-date/received-date.0.xml, src/test/resources/peer-review/article-received-date/received-date.1.xml, src/test/resources/peer-review/article-received-date/received-date.2.xml, src/test/resources/peer-review/article-received-date/received-date.3.xml, src/test/resources/peer-review/peer-review.pone.0207232.xml, src/test/resources/peer-review/pone.0207232.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-835
This PR fetches and displays the specified metadata in the peer review history.
Specifically, it gets the "received date" (aka, original submission date) from
the article xml. The editor and author/decision letter dates are retrieved
from the TPR payload.
I suspect this PR will need at least one more round of edits before accepting
and merging. Here are some ponderables. Reviewer may discover other issues.
1. Should we rename the received-date tag? article-received-date seems a better
name, or other ...
2. I put received date inside of the peer-review xml block, but maybe it should go
elsewhere. you'll see some explicit references to this node in the template. i
defined a no-op template matcher to ignore this node …
=> AMBR-835: TPR Metadata

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-817
Upgrades springsecurity.
=> AMBR-817 Upgrade springsecurity

pom.xml
This reverts commit 732d0cdb1dac887da745f3f336f69706f793a995.
This broke with
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.util.AntPathMatcher.setCaseSensitive(Z)V
org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) …
```
=> Revert "AMBR-817 Upgrade springsecurity"

pom.xml
> molten, plos-formulas, other applications
>Explain in a few sentences what functionality changed, and how you approached those changes. Don't be afraid to give a little extra detail. The Reviewer is going to read the original ticket, but this can point them in the right direction.
=> updating pom version to 3.7.8-SNAPSHOT

pom.xml, src/main/java/org/ambraproject/wombat/config/site/SiteTemplateLoader.java, src/main/java/org/ambraproject/wombat/controller/AppRootPage.java, src/main/java/org/ambraproject/wombat/controller/ExceptionHandlerAdvisor.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-817
The core of this is upgrading springsecurity to deal with a security issue. However, upgrading this meant that we needed to upgrade a few other packages as well.
I needed to fix the 404 handling when there is no "site" selected. You should test this by visiting http://localhost:8080/xyz, for instance. This should give you a very plain 404 site and no error.
=> AMBR-817 part 2

src/main/resources/peer-review-transform.xsl, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceImplTest.java, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceTest.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-857
Presents the review DOI as a link to doi.org at the bottom of the review.
=> AMBR-857 show review doi link

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-916
Upgrades gson to fix a known issue: 
https://github.com/google/gson/issues/440
https://github.com/google/gson/pull/1075
I was not able to reproduce due to an incomplete vagrant setup.  My attempt to search:
http://journals.vagrant.local/plosone/dynamicSearch?filterJournals=PLoSONE&q=cells
gets the following error:
`org.ambraproject.wombat.service.EntityNotFoundException: Entity /v2/journals/PLoSBiology not found`
This issue is blocking a release so I'm going to submit the PR and see if we can find a more expedient way to confirm the presumed fix, either by updating my vagrant or testing it on another dev's vagrant, or test it in the dev environment. 
=> AMBR-916 upgrade gson to avoid stack overflow error on search

src/main/webapp/WEB-INF/themes/mobile/ftl/article/articleSuffix.ftl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-843
adds a link on the mobile article page to peer review content if present 
=> AMBR-843 mobile pages links to peer review if present

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-935
Scopes mockito correctly - it is only used in tests.
=> AMBR-935 Scope mockito to test

pom.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-932
Removes a dependency that is not used.
=> AMBR-932 Remove unused aspectj dependency

src/main/webapp/WEB-INF/themes/desktop/sass/_components.scss, src/main/webapp/WEB-INF/themes/desktop/sass/search-results.scss, src/main/webapp/WEB-INF/themes/desktop/sass/vendor/foundation/components/_pagination.scss, src/main/webapp/WEB-INF/themes/desktop/sass/vendor/foundation/components/_tooltips.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-898
@gt-plos reported two regressions after merging my changes:
Dropdown lists: 'Sort By" and pagination ("Results per page") are very difficult to click
on the search result page:
https://journals-dev.plos.org/plosone/search?q=cell&filterJournals=PLoSONE
I reverted the relevant CSS.
=> Ambr 898 fix css validation errors

src/main/webapp/WEB-INF/themes/root/resource/js/components/metrics_saved_section.js
> https://github.com/PLOS/plos-themes/pull/967
>Hopefully just removes the citeulike box from the 'Saved' section on the metrics tab.
=> AMBR-949 remove citeulike from metrics_saved_section.js

src/main/webapp/WEB-INF/themes/mobile/resource/css/peer-review.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-933
Peer review tab layout on mobile was affected by long URLs that were printed in full within the Decision Letter.  Since URLs can't be broken into "words", the browser treats them as one long word and as a block element (pushing the content beyond the viewport).
I addressed this with a bit of a work-around:
- Set the font-size of the link text to zero
- Leveraged the `::after` selector to replace the link text with a generic `[LINK]`
The content now flows as expected:
If I made any …
=> Ambr 933 decision letter mobile

src/main/webapp/WEB-INF/themes/mobile/resource/css/peer-review.css
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-933
Added back a line of CSS (thanks, Shawn!) that targets supplemental files container and the DOI URL.  This should force the review content to flow inside the width of the device.
=> AMBR-933 Address filename length and doi length

src/main/java/org/ambraproject/wombat/service/remote/ArticleSearchQuery.java, src/main/java/org/ambraproject/wombat/service/remote/SolrSearchApiImpl.java, src/main/webapp/WEB-INF/themes/desktop/ftl/article/signposts.ftl, src/main/webapp/WEB-INF/themes/mobile/ftl/search/searchResults.ftl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-978
Removes all references to the defunct citeulike.
Should we also remove this stuff from ALM proper?
=> AMBR-978 Remove citeulike

pom.xml
> molten, plos-formulas, other applications
>Explain in a few sentences what functionality changed, and how you approached those changes. Don't be afraid to give a little extra detail. The Reviewer is going to read the original ticket, but this can point them in the right direction.
=> Merge back v3.7.9 and update pom

src/main/webapp/WEB-INF/themes/desktop/resource/js/components/search_results_alm_ajax.js
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-978
Display only Mendeley saves in search results
=> AMBR-978 Fix ALM save report on search results

pom.xml
> molten, plos-formulas, other applications
>Explain in a few sentences what functionality changed, and how you approached those changes. Don't be afraid to give a little extra detail. The Reviewer is going to read the original ticket, but this can point them in the right direction.
=> Merge back from RC and update pom to 3.7.11-SNAPSHOT

pom.xml
merge back and update pom to 3.7.12-SNAPSHOT
=> Cut3.7.11 update to 3.7.12-SNAPSHOT

src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/relatedArticles.ftl, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-1034
Present links to related article's PDF as well as HTML.
Originally we thought all related articles would have a printable file. We discovered a type that does not: annotations. The related article model does not already contain information about the article's files so we don't know if it has a printable.  Adding that to the model would add complexity to the ticket and the system. We went for a cheap way to identify annotations by analyzing the article DOI. 
=> AMBR-1034 link to related article pdfs

src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/relatedArticles.ftl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-1034
=> AMBR-1034 remove underlined space at end of link

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_static-publish.scss
> molten, plos-formulas, other applications
>Explain in a few sentences what functionality changed, and how you approached those changes. Don't be afraid to give a little extra detail. The Reviewer is going to read the original ticket, but this can point them in the right direction.
=> Ambr 1054 why pub with pone

src/main/webapp/WEB-INF/themes/mobile/ftl/article/articlePrefix.ftl
https://jira.plos.org/jira/browse/AMBR-1035
I messed up the mobile display :(
Original (in production)
Previous (broken) version (currently in dev):
After this change (fixed):
=> AMBR-1035 Fix amendments for mobile

src/main/java/org/ambraproject/wombat/model/RelatedArticleType.java, src/main/webapp/WEB-INF/themes/desktop/ftl/article/amendmentGroupTitle.ftl
Fix for https://jira.plos.org/jira/browse/AMBR-1069?focusedCommentId=271219&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-271219
=> AMBR-1069 Show preceding article citation in updating articles

README.md
Document environment variable configuration in README.
=> Add environment variable configuration information to README

src/main/webapp/WEB-INF/themes/desktop/xform/article-transform.xsl, src/main/webapp/WEB-INF/themes/mobile/xform/article-transform.xsl
=> ENG-16 Move colon inside strong tag

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss
https://jira.plos.org/jira/browse/ENG-89
Before:
After:
=> ENG-89 Fix reference number alignment when more than 1000 references

src/main/webapp/WEB-INF/themes/mobile/resource/css/mobile.css
https://jira.plos.org/jira/browse/ENG-89
I'm sorry, I didn't fix it for mobile. :(
=> ENG-89 Fix reference number alignment when > 1000 references: mobile

src/main/webapp/WEB-INF/themes/desktop/sass/sections/_header.scss
See https://github.com/PLOS/plos-themes/pull/1062
=> ENG-124 Remove extra margin in logos

src/main/java/org/ambraproject/wombat/config/RuntimeConfiguration.java, src/main/java/org/ambraproject/wombat/config/RuntimeConfigurationImpl.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/test/java/org/ambraproject/wombat/config/TestRuntimeConfiguration.java
Merging recent changes from develop into the docker branch
=> Docker merge develop

src/main/webapp/WEB-INF/themes/mobile/ftl/article/articleSuffix.ftl
=> ENG-116 use HTTPS for plos resolver

src/main/webapp/WEB-INF/themes/mobile/resource/css/interface.css
https://jira.plos.org/jira/browse/ENG-111
related: https://github.com/PLOS/plos-themes/pull/1067
style to center the logo and add a little bottom margin
=> ENG-111 center logo

src/main/webapp/WEB-INF/themes/desktop/ftl/article/figure_carousel.ftl, src/main/webapp/WEB-INF/themes/desktop/xform/article-transform.xsl
https://jira.plos.org/jira/browse/ENG-227
Loads thumbnails for desktop view lazily!
=> ENG-227 lazy load thumbnails desktop

src/main/webapp/WEB-INF/themes/desktop/sass/sections/home/_subscription.scss
https://jira.plos.org/jira/browse/ENG-291
see: https://github.com/PLOS/plos-themes/pull/1074
=> ENG-291 retain style

solr/README.md, solr/config/admin-extra.html, solr/config/admin-extra.menu-bottom.html, solr/config/admin-extra.menu-top.html, solr/config/author_stopwords.txt, solr/config/elevate.xml, solr/config/managed-schema, solr/config/mapping-ISOLatin1Accent.txt, solr/config/protwords.txt, solr/config/scripts.conf, solr/config/solrconfig.xml, solr/config/stopwords.txt, solr/config/synonyms.txt, solr/config/xslt/atom.xsl, solr/config/xslt/default.xsl, solr/config/xslt/rss.xsl
This PR imports the `journals_v1_0_3` configuration from solr-mega-prod, which is the configuration currently in use by the production journals stack.  If some other configuration would be better suited to check in here, please let me know.  
It also adds a `README` with instructions for managing solr configs via docker.
Is there anything else that should go in here?
=> ENG-195 solr configs and README
