PLOS/wombat

src/main/java/org/ambraproject/wombat/controller/LockssController.java, src/main/webapp/WEB-INF/themes/root/config/mappings.yaml
If not disabled, it causes handler mapping collisions on any site that is
not mapped with a site token.
=> DPRO-3416: Disable "lockssYears" handler by default

src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/sidebar.ftl
Change in template to invert order of appearance of ad an Subject Area widget.
=> DPRO-3452 Changing skyscraper ad position

src/main/java/org/ambraproject/wombat/identity/RequestedDoiVersion.java
@msingh05 
@anilop 
Very simple fix. Google Analytics should be unaffected
=> DPRO-3487: trim incoming doi requests in wombat to ignore trailing %20s

pom.xml
The root (`/`) context is used by rhino and wombat when starting with the tomcat maven plugin. This changes wombat to use it also.
=> Use / as the path when starting wombat with mvn tomcat6:run

src/main/java/org/ambraproject/wombat/config/YamlConfiguration.java
Previously, if `wombat.yaml` did not define a `solr` heading, this code would throw a NPE.
```
...
Caused by: java.lang.NullPointerException
at org.ambraproject.wombat.config.YamlConfiguration$SolrConfigurationInput.access$2100(YamlConfiguration.java:485)
at org.ambraproject.wombat.config.YamlConfiguration.validate(YamlConfiguration.java:256)
at org.ambraproject.wombat.config.RootConfiguration.runtimeConfiguration(RootConfiguration.java:92)
at org.ambraproject.wombat.config.RootConfiguration$$EnhancerBySpringCGLIB$$efdbbf06.CGLIB$runtimeConfiguration$2(<generated>)
at org.ambraproject.wombat.config.RootConfiguration$$EnhancerBySpringCGLIB$$efdbbf06$$FastClassBySpringCGLIB$$795f1b7c.invoke(<generated>)
```
This prevents the NPE by testing if `input.solr` is `null` before calling …
=> Make solr configuration optional

pom.xml
Set a default value for `maven.tomcat.port`.
=> Use 8080 as port when started by mvn tomcat plugin

src/deb/control/postinst
debian packages should not clear the questions answered when installing. This
should happen when the package is purged.
=> AMBR-3 debian: do not db_purge in postinst

src/main/webapp/WEB-INF/themes/desktop/xform/article-transform.xsl
This PR removes the trailing '.' at the end of the DOI reference for non-article types.
=> AMBR-205 : Removed trailing '.' for non-journal references.

src/main/webapp/WEB-INF/themes/desktop/ftl/common/header/browse.ftl
This PR replaces the link from `/s/help-using-this-site#loc-subject-areas` to `https://github.com/PLOS/plos-thesaurus/blob/develop/README.md`.
=> AMBR-387 : Replaced help using this site link.

src/main/webapp/WEB-INF/themes/desktop/ftl/article/comment/comment.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/comment/comments.ftl
This PR forces the `comment.title` to be escaped so that HTML tags are rendered as literal strings.  For example, it escapes:
```
< > & "  '
```
as
```
&lt; &gt; &amp; &quot; &#39;
```
=> AMBR-420 : Explicitly HTML escaped the comment title.

src/main/webapp/WEB-INF/themes/desktop/ftl/search/searchTemplates.ftl
This PR escapes the query string from the search pages that are rendered via the JavaScript based templates.
=> AMBR-429 : Forced escaping of search query string.

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss, src/main/webapp/WEB-INF/themes/mobile/resource/css/mobile.css, src/main/webapp/WEB-INF/themes/root/ftl/article/authorItem.ftl
This PR fixes the ORCID image not rendering properly on mobile, by adding CSS to allow image and text to be on the same row.
=> AMBR-422 : CSS Styling to fix author page on mobile.

src/main/webapp/WEB-INF/themes/desktop/ftl/error/error.ftl, src/main/webapp/WEB-INF/themes/mobile/ftl/error/error.ftl, src/main/webapp/WEB-INF/themes/root/app/error.ftl, src/main/webapp/WEB-INF/themes/root/ftl/error/error.ftl
This PR explicitly HTML escapes the rendered stacktrace.  However, it looks like the template to render the wombat error page is in [plos-themes](https://github.com/PLOS/plos-themes/blob/develop/code/desktop/all_sites/ftl/error/error.ftl).   So, there's a correspond [PR](https://github.com/PLOS/plos-themes/pull/897) in **plos-themes** to fix the XSS issue.
=> AMBR-439 : Explicitly HTML escaped the rendered stacktrace.

src/main/webapp/WEB-INF/themes/mobile/ftl/common/bodyJs.ftl
We were not including the right libraries in mobile and those libraries are dependent on the correct version of Jquery.
updated Jquery
added underscore to mobile JS
contains matching plos-themes pull request -  PLOS/plos-themes#899
=> AMBR-473 - get ed board working on mobile

src/test/java/org/ambraproject/wombat/service/CommentFormattingTest.java
We decided not to force links within comments to be https. We will do this work in separate ticket.
=> AMBR-556 revert test for code we pulled out

src/main/webapp/WEB-INF/themes/desktop/resource/js/pages/article_references.js
When the view article link is clicked we query crossref search API for the article via the http endpoint.  in https this causes a CORS error. calling the API through https fixes the error.
=> AMBR-574 - call crossref search API via HTTPS

src/deb/tomcat7/conf/server.template.xml
When viewing a `server.xml` file on a server using a pager, e.g. `less`, comments are hard to tell apart from active configuration. This PR removes all inactive configuration and inappropriate comments from `server.xml`.
=> Remove commented configuration in server.xml

pom.xml
The `develop` branch should always have a `SNAPSHOT` version.
=> Bump version to 3.7.2-SNAPSHOT

pom.xml
By installing in `wombat.war`, a user will need to visit: `http://hostname:PORT/wombat/` to see rhino.
Our salt scripts all rename `wombat.war` to `ROOT.war` to listen at `http://hostname:PORT/`
This is overly complicated, in my opinion. Why not simply put it in `ROOT.war` in the debian package and skip the salt step?
Advantages:
- Installing the debian package works properly, and we do not need to run salt afterwards to get the proper setup
- Reduces the amount of salt code
This should be safely mergeable without any change to salt, because the salt file move will noop if not necessary, and we can remove the salt code later.
=> AMBR-3 debian: install wombat in root context

src/main/java/org/ambraproject/wombat/controller/ArticleMetadata.java, src/test/java/org/ambraproject/wombat/controller/ArticleMetadataTest.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-631
https://github.com/PLOS/wombat/pull/1471
PeerReview tab was showing for all articles.  This adds tests to confirm that TPR will be null when no peer review items are present.  
Returning null is consistent with the rest of the doPopulate() method.
~~- [ ] Confirmed unique - we aren't using something similar elsewhere~~
~~- [ ] License comports with our licensing (MIT preferable)~~
~~- [ ] Pull requests are created to change the files in molten or in SALT-formulas.~~
~~- [ ] DB migration scripts are created and this detail is added to testing notes in the ticket.~~
=> peerReview is null when there are no peer review items

PULL_REQUEST_TEMPLATE.md
Remove two checkboxes in the pull request template that were so vague as to be impossible to complete.
Remove 2 checkboxes for the reviewer in the pull request template that were impossible to do, because they were so vague or had a broken link.
=> Remove impossible tasks

src/main/java/org/ambraproject/wombat/service/PeerReviewServiceImpl.java, src/main/java/org/ambraproject/wombat/service/SiteTransformerFactory.java
*JIRA issue:* https://jira.plos.org/jira/browse/-AMBR-822
Explicity uses an XML transformer that supports XSL transforms.  We were using a default transformer before this change, but we found that on tomcat 8 with the cargo runner the default transformer does not seem to support XSL.  As a result the Peer Review content is a wall unformatted text.
This issue is not present in the [dev environment](https://journals-dev.plos.org/plosone/article/peerReview?id=10.1371/journal.pone.0207232)
Noting that we still don't know what exactly would need to be changed in the local cargo-run environment to have parity with dev in regards to the default transformer. We have chosen not to prioritize further investigation.
=> AMBR-822 explicitly use saxon transformer

pom.xml, src/deb/control/config, src/deb/control/postinst, src/deb/control/templates, src/deb/tomcat8/conf/server.template.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-822
Cleans up a few issues with AMBR-822:
- Sets cargo to use the tomcat we have installed on our current boxes, 8.0.32
- Uses 8080 as the port that tomcat listens on when running locally
- Disables the shutdown port in tomcat, which is not needed on linux
- Uses a random port for JMX, preventing possible port conflicts
- Only installs deb package in `/var/tmp/apt` in the `install` maven goal
=> Ambr 822 part 2

src/main/java/org/ambraproject/wombat/freemarker/ReplaceParametersDirective.java, src/test/java/org/ambraproject/wombat/freemarker/ReplaceParametersDirectiveTest.java
In tomcat8, presumably because it supports a different version of the servlet spec, the type of the variables passed in to freemarker can be either a String[] or an AbstractList<String>.
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-886
Handles both cases.
To test, run:
`mvn cargo:run`
locally and visit:
http://localhost:8080/plosone/browse/geographical_locations?resultView=cover
If this works, you should not see an error.
You may need to configure your wombat properly. Check with me if your current config does not work.
=> AMBR-886 Fix issue with upgrade to tomcat8

src/main/java/org/ambraproject/wombat/controller/ArticleController.java, src/test/java/org/ambraproject/wombat/controller/ArticleControllerTest.java
Extracts and renames some methods to clarify what the article controller is doing when it gets the article HTML. 
This is a straight refactor.  Does it make what is happeneing clearer to you?
=> rename and extract methods for clarity

pom.xml, src/deb/tomcat8/conf/server.template.xml, src/main/webapp/WEB-INF/web.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-906
This work came out of work on https://jira.plos.org/jira/browse/AMBR-905
While doing that, I noticed that we were using a webapp filter to perform gzip compression on the fly. This can be handled in the tomcat container, which simplifies the application.
The configuration for which content is gzipped may have changed somewhat, but you can see that HTML is being compressed:
js: 
and css:
Testing with `ab` (apache benchmark) shows similar performance as before:
Before change (and after warming up wombat):
```
👉 ab -l -c 10 -n 1000 -H "Accept-Encoding: gzip,deflate" http://journals.vagrant.local/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to …
```
=> AMBR-906 Use gzip compression in tomcat, not webapp

pom.xml
Also change to build in prepare-package phase, speeding up test builds.
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-914
Increases the version of the plugin used to run gulp.
Also, changes the *phase* that these steps are run in to `prepare-package`. These files are not needed for the java tests, and this speeds up testing substantially by not building CSS files until they are needed.
=> AMBR-914 Bump frontend-maven-plugin version to 1.7.5

src/main/webapp/WEB-INF/themes/desktop/xform/article-transform.xsl, src/main/webapp/WEB-INF/themes/mobile/xform/article-transform.xsl
Reconciles immaterial differences in comments and whitespace between our mobile and desktop article xsl.  These diffs obscure the material differences and make it extra intimidating to make any edits.  
Post-clarification we can more easily identify differences that appear unintentional and may be bugs. We can also identify tech debt where we have chosen to make changes in xsl that could more easily be done in CSS (with features which may not have been broadly supported at the time the xsl was written).
Vast swathes of the mobile and desktop xsl are identical. Individual tags like `<citation>` have minor differences that may not be meaningful but we're afraid to touch it, partially because it's buried in immaterial differences.
I do not believe we have a means to test these changes …
=> Empowerment - xsl clarity

src/deb/tomcat8/conf/server.template.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-906
I messed this one up. It turns on the compression was happening in apache, not in tomcat. This is the correct option to use.
See https://tomcat.apache.org/tomcat-8.5-doc/config/http.html
Now we will have compression in both tomcat and apache. This is fine. See https://jira.plos.org/jira/browse/AMBR-862?focusedCommentId=245360&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-245360 for some tests I did comparing the various gzip filters being enabled.
=> AMBR-906 Fix compression option

pom.xml, src/test/java/org/ambraproject/wombat/config/site/url/LinkTest.java, src/test/java/org/ambraproject/wombat/config/theme/TestTheme.java, src/test/java/org/ambraproject/wombat/config/theme/ThemeGraphTest.java, src/test/java/org/ambraproject/wombat/controller/ArticleControllerTest.java, src/test/java/org/ambraproject/wombat/controller/ArticleMetadataTest.java, src/test/java/org/ambraproject/wombat/controller/CommentControllerTest.java, src/test/java/org/ambraproject/wombat/controller/ControllerTest.java, src/test/java/org/ambraproject/wombat/controller/PeerReviewControllerTest.java, src/test/java/org/ambraproject/wombat/controller/SearchControllerTest.java, src/test/java/org/ambraproject/wombat/controller/StaticResourceControllerTest.java, src/test/java/org/ambraproject/wombat/controller/TaxonomyControllerTest.java, src/test/java/org/ambraproject/wombat/freemarker/HtmlElementTransformationTest.java, src/test/java/org/ambraproject/wombat/freemarker/ReplaceParametersDirectiveTest.java, src/test/java/org/ambraproject/wombat/freemarker/asset/RenderAssetsDirectiveTest.java, src/test/java/org/ambraproject/wombat/model/SearchFilterFactoryTest.java, src/test/java/org/ambraproject/wombat/service/ArticleResolutionServiceTest.java, src/test/java/org/ambraproject/wombat/service/AssetServiceTest.java, src/test/java/org/ambraproject/wombat/service/CommentFormattingTest.java, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceTest.java, src/test/java/org/ambraproject/wombat/service/SearchFilterServiceTest.java, src/test/java/org/ambraproject/wombat/service/remote/SolrSearchApiTest.java, src/test/java/org/ambraproject/wombat/util/CacheKeyTest.java, src/test/java/org/ambraproject/wombat/util/GitInfoTest.java, src/test/java/org/ambraproject/wombat/util/HttpMessageUtilTest.java, src/test/java/org/ambraproject/wombat/util/TextUtilTest.java
junit is a more standard library and has better integration with IDEs.
junit is a more standard java testing library. It has better support in eclipse and netbeans. It is almost indistinguishable in the way that we use it from testng. It is used in content-repo.
Also, junit 5 is a nice looking, very modern java library, if we ever want to upgrade.
=> Switch to junit

src/main/resources/peer-review-transform.xsl, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceImplTest.java, src/test/resources/peer-review/peer-review.pone.0207232.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-922
> Display as many editors as there are present in the sub-article xml
=> AMBR-922 display multiple editors

src/deb/tomcat8/conf/server.template.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-672
https://github.com/PLOS/molten/pull/1185
Removes references to `tomcat-users.xml` file, which will no longer be created in salt.
=> AMBR-672 Remove references to tomcat-users.xml file

src/main/resources/peer-review-transform.xsl, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_peer-review.scss, src/main/webapp/WEB-INF/themes/mobile/resource/css/base.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/interface.css, src/main/webapp/WEB-INF/themes/mobile/resource/css/peer-review.css, src/main/webapp/WEB-INF/themes/mobile/xform/article-transform.xsl
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-864
Presents a MVP set of JATS tags on the Peer Review page.
The peer review XSL continues to be device-agnostic thus avoiding separate transforms for mobile and desktop. The intent is to handle any differences in CSS. To this end 77b9b9233637a5241aa3c9e72a015bf0009abca0 reconciles a needless difference between the mobile and desktop article transforms with regards to the class applied to a `<ul>`.
[See the ticket](https://jira.plos.org/jira/browse/AMBR-864?focusedCommentId=247607&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-247607) For a comparison of the article and peer review pages.
I've tested in a container with wombat referring to the dev rhino.  Example URL: …
=> Ambr 864 jats

src/main/java/org/ambraproject/wombat/service/PeerReviewServiceImpl.java, src/main/resources/peer-review-transform.xsl, src/test/java/org/ambraproject/wombat/service/PeerReviewServiceImplTest.java, src/test/resources/peer-review/peer-review.pone.0207232.xml
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-954
Displays editor names for acceptance letters in the same manner as for decision letters
Most of these changes are cleanup.  The actual feature was added in 1d1e88bb3330fcdcabfcf08d138527e77926a911
=> Ambr 954 acceptance letter editors

src/main/webapp/WEB-INF/themes/desktop/resource/js/pages/search_results.js
*JIRA issue:* https://jira.plos.org/jira/browse/SERV-192
specifies the character encoding when making an ajax request for search results
I was confused because the dev solr collection has misencoded content.  We need to fix that:
[dev solr](http://solr-mega-dev.soma.plos.org/solr/journals_dev/select/?wt=json&fq=doc_type%3Afull&fq=!article_type_facet%3A%22Issue+Image%22&rows=1&hl=false&q=HIF-1%CE%B1+Expression+Produces+a+Reversible+Cardiomyopathy&defType=dismax&facet=false&fl=id%2Ceissn%2Cpublication_date%2Ctitle%2Ctitle_display%2Cjournal_name%2Cauthor_display%2Carticle_type%2Ccounter_total_all%2Calm_scopusCiteCount%2Calm_citeulikeCount%2Calm_mendeleyCount%2Calm_twitterCount%2Calm_facebookCount%2Cretraction%2Cexpression_of_concern%2Cstriking_image%2Cfigure_table_caption%2Cjournal_key&sort=s …
=> SERV-192 UTF-8 encoded search results

src/main/webapp/WEB-INF/themes/desktop/resource/js/components/signposts.js
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-978
Only displays mendeley saves in the "signpost" data, to align with data in the metrics page.
Example. On dev, we see (https://journals-dev.plos.org/ploscompbiol/article/metrics?id=10.1371/journal.pcbi.1000112)
But on the signpost:
With this code, we see on the signpost:
=> AMBR-978 Only display Mendeley results in signpost

src/main/java/org/ambraproject/wombat/controller/ArticleMetadata.java, src/main/webapp/WEB-INF/themes/desktop/ftl/article/amendment.ftl, src/main/webapp/WEB-INF/themes/desktop/sass/_utilities.scss, src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article-body.scss
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-1033
Amendments (like Corrections, Retractions, and now Update Article) are displayed in the top center of the related article.  ex: https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001786
This change gives the amendment a journal-branded background color.  Specific amendment types can override the background color via CSS, as Correction, Retraction, and EOC continue to do.
I removed a couple of "callout" mixins that were adding complexity where IMO it wasn't needed.
=> Ambr 1033 branded citations

pom.xml, src/main/java/org/ambraproject/wombat/service/remote/UserApiImpl.java
Required a switch in Base64 library.
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-936
This library was doing nothing except providing a base64 implementation, which is built in to java.
=> AMBR-936 Remove dependency on xom

pom.xml, src/main/java/com/google/gson/typeadapters/UtcDateTypeAdapter.java, src/main/java/org/ambraproject/wombat/cache/Cache.java, src/main/java/org/ambraproject/wombat/cache/GuavaCache.java, src/main/java/org/ambraproject/wombat/cache/MemcacheClient.java, src/main/java/org/ambraproject/wombat/cache/NullCache.java, src/main/java/org/ambraproject/wombat/config/RootConfiguration.java, src/main/java/org/ambraproject/wombat/service/AssetServiceImpl.java, src/main/java/org/ambraproject/wombat/service/BrowseTaxonomyServiceImpl.java, src/main/java/org/ambraproject/wombat/service/RecentArticleServiceImpl.java, src/main/java/org/ambraproject/wombat/service/remote/CachedRemoteService.java, src/main/java/org/ambraproject/wombat/util/CacheUtil.java, src/test/java/com/google/gson/typeadapters/UtcDateTypeAdapterTest.java, src/test/java/org/ambraproject/wombat/cache/GuavaCacheTest.java, src/test/java/org/ambraproject/wombat/config/TestSpringConfiguration.java, src/test/java/org/ambraproject/wombat/controller/ControllerTestConfiguration.java
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-881
Eliminates use of the rhombat library, which complicates builds.
- Move caching from rhombat to wombat
- Use UtcDateTypeAdapter from google
- Use DateUtils from httpclient
=> AMBR-881 Remove rhombat dependency

src/main/java/org/ambraproject/wombat/model/RelatedArticleType.java, src/main/webapp/WEB-INF/themes/desktop/ftl/article/amendment.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/amendmentGroupTitle.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/relatedArticleTypeHeader.ftl, src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/relatedArticles.ftl
https://jira.plos.org/jira/browse/AMBR-1074
See also: https://github.com/PLOS/plos-themes/pull/1016
To test, point your local wombat at dev rhino by editing your `wombat.yaml` config:
```
🤔 head ~/c/ambra/config/wombat.yaml 
server: http://rhino-201.soma.plos.org:8006/v2/
...
```
and view:
http://localhost:8080/DesktopPlosBiology/article?id=10.1371/journal.pbio.9000098
http://localhost:8080/DesktopPlosBiology/article?id=10.1371/journal.pbio.1002593
http://localhost:8080/DesktopPlosOne/article?id=10.1371/journal.pone.0212527
If you want to test the custom theme for PLOS One only (https://github.com/PLOS/plos-themes/pull/1016) the only way I was able to do this was to copy the theme `ftl` files to my local themes dir:
```
🤔 pwd
/home/egh/c/plos-themes
🤔 rsync -a …
```
=> AMBR-1074 Extract header for amendments, related sidebar

src/main/webapp/WEB-INF/themes/mobile/ftl/article/articlePrefix.ftl
In freemarker, apparently one cannot access a null value at all.
=> AMBR-1074 Fix call to specificUse

pom.xml
http no longer works.
Simple fix for `cargo:run`.
=> Use https to fetch from maven.org

src/main/webapp/WEB-INF/themes/root/ftl/redirect.ftl
http://journals.vagrant.test/plosone/redirect/guidelines#fungal
You should no longer see a 403 error in the Network tab of your browser tools when you invoke a client-side redirect. You will, however, get a 404 because there is no static page service configured in vagrant
compare to:
https://journals-dev.plos.org/plosone/redirect/guidelines#fungal
=> AMBR-1103 stop calling nonexistent redirect logging service

src/main/webapp/WEB-INF/themes/desktop/sass/pages/_article.scss, src/main/webapp/WEB-INF/themes/desktop/sass/sections/_header.scss
https://jira.plos.org/jira/browse/AMBR-1108
companion PR in plos-themes: https://github.com/PLOS/plos-themes/pull/1028
This replaces the journal logos on desktop, mobile and in print.  
To package wombat and deploy to vagrant
```
cd ../plos-themes && git checkout AMBR-1108
cd ../wombat && git checkout AMBR-1108
mvn clean install
cd ~/pogos2/vagrant/apps/journals
vagrant destroy -f && vagrant up
./seed
```
Copy changes from plos-themes to vagrant
```
cd plos-themes/..  # the next line must be run from the parent dir of the plos-themes repo
find plos-themes \( -name 'plos-interface.css' -or -name 'logo.png' \) -exec cp --parents \{\} ~/pogos2/vagrant/apps/journals/ \;
cd ~/pogos2/vagrant/apps/journals
vagrant ssh
cp -r /vagrant/apps/journals/plos-themes/* /opt/plos/wombat/var/themes/
rm …
```
=> AMBR-1108 logo is below the top nav

src/main/webapp/WEB-INF/themes/desktop/resource/js/components/blogfeed.js
https://jira.plos.org/jira/browse/AMBR-1144
Unfortunately, because of CORS I couldn't test this, I just get an error. :crossed_fingers: it works.
See also https://github.com/PLOS/plos-themes/pull/1051
=> AMBR-1144 Rename generic_blogfeed to logo-plos-imageonly

src/main/webapp/WEB-INF/themes/desktop/xform/article-transform.xsl, src/main/webapp/WEB-INF/themes/mobile/xform/article-transform.xsl
https://jira.plos.org/jira/browse/ENG-16
To test, point your wombat instance at dev rhino (journals-dev1-backend1.soma.plos.org) and check out
http://localhost:8080/MobilePlosBiology/article?id=10.1371/journal.pbio.2006421
http://localhost:8080/DesktopPlosBiology/article?id=10.1371/journal.pbio.2006421
Desktop:
Mobile:
Other articles should display the same as before.
=> ENG-16 Add note to Preregistered Research Report articles

src/main/java/org/ambraproject/wombat/config/RuntimeConfiguration.java, src/main/java/org/ambraproject/wombat/config/YamlConfiguration.java, src/main/java/org/ambraproject/wombat/controller/AppRootPage.java, src/main/java/org/ambraproject/wombat/controller/ExceptionHandlerAdvisor.java, src/test/java/org/ambraproject/wombat/config/TestRuntimeConfiguration.java
https://jira.plos.org/jira/browse/ENG-67
I refactored the way the "debug" page is displayed so that it is never displayed if the `env` setting is set to `prod` (the default).
=> ENG-67 Redirect to URL on startup (do not display root page)

src/main/webapp/WEB-INF/themes/desktop/ftl/article/aside/print.ftl
https://jira.plos.org/jira/browse/ENG-80
Fix spacing on print link
After this fix: 
See JIRA ticket for problem.
=> ENG-80 Fix spacing on print link

src/main/java/org/ambraproject/wombat/service/remote/ArticleSearchQuery.java, src/test/java/org/ambraproject/wombat/service/remote/SolrSearchApiTest.java
in ENG-119, I rewrote a lot of the query generation code, but I broke existing logic which did a wildcard query when the search was empty. This broke the search that you get when you click on a subject.
Compare (broken): https://journals-dev.plos.org/plosone/search?filterSubjects=Beetles&filterJournals=PLoSONE&q= with (working) https://journals.plos.org/plosone/search?filterSubjects=Beetles&filterJournals=PLoSONE&q=
Screenshot of this working locally after this change:
=> ENG-119 Use *:* as solr query when the query is the empty string

src/main/java/org/ambraproject/wombat/model/SearchFilterFactory.java, src/main/java/org/ambraproject/wombat/service/BrowseTaxonomyServiceImpl.java, src/main/java/org/ambraproject/wombat/service/SearchFilterService.java, src/main/java/org/ambraproject/wombat/service/remote/ArticleSearchQuery.java, src/main/java/org/ambraproject/wombat/service/remote/SolrQueryBuilder.java, src/test/java/org/ambraproject/wombat/service/remote/SolrSearchApiTest.java
https://jira.plos.org/jira/browse/ENG-119
Fix for problem #2 identified by @gt-plos  here https://jira.plos.org/jira/browse/ENG-119?focusedCommentId=281957&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-281957
Explanation: Article type and journal are facets that should be ORed together, not ANDed together. That is, when a user is attempting to facet, they want articles in ONE **OR** Medicine, not both in ONE **AND** Medicine (which is impossible). In order to support this, we need to exclude certain facet queries from the faceting mechanism. That is, we want to return facet counts as though the facet query did not happen, because we want to return the counts that a user would get if they added an OR clause
to the facet query. Fortunately, solr supports …
=> ENG-119 Fix problem with journal, article type faceting
